### ISSUE TITLE
Conflict between 2 mods.

### ISSUE THREAD

**Issue by igotfits1** [rmnaderdev/Whitelist-Sync-2#26]
E:\- ATM8 - 1.0.15>title 0-ATM8 (v 1.0.15)

E:\- ATM8 - 1.0.15>java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.2.8/win_args.txt nogui -jar
2023-03-28 13:43:51,834 main WARN Advanced terminal features are not available in this environment
[13:43:51] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.8, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, nogui, -jar]
[13:43:51] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.6 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[13:43:53] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/-%20ATM8%20-%201.0.15/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[13:43:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\- ATM8 - 1.0.15\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.8\fmlcore-1.19.2-43.2.8.jar is missing mods.toml file
[13:43:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\- ATM8 - 1.0.15\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.8\javafmllanguage-1.19.2-43.2.8.jar is missing mods.toml file
[13:43:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\- ATM8 - 1.0.15\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.8\lowcodelanguage-1.19.2-43.2.8.jar is missing mods.toml file
[13:43:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\- ATM8 - 1.0.15\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.8\mclanguage-1.19.2-43.2.8.jar is missing mods.toml file
[13:43:54] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: E:\- ATM8 - 1.0.15\mods\resourcefullib-forge-1.19.2-1.1.23.jar
[13:43:54] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: botarium. Using Mod File: E:\- ATM8 - 1.0.15\mods\botarium-forge-1.19.2-1.8.2.jar
[13:43:54] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 18 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules dcintegration and whitelistsync2 export package org.sqlite.javax to module dungeons_arise
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

E:\- ATM8 - 1.0.15>timeout 10

Waiting for  7 seconds, press a key to continue ...

**Comment by igotfits1** [comment]
Hi Potato!!!! Hope you remember me, Ive been using your mod for years on all my servers. Im having an issue now with dcintegrations and yours, for some reason I cant update to the latest dcintegrations and its a must since discord updates alot also. Can you take a look? I would love to keep both mods running since I depend on them both heavily! Thanks!

**Comment by rmnaderdev** [comment]
Should be fixed in v2.5.0 now that I am not shadowing the JDBC jar files. https://modrinth.com/mod/wlsync2/version/1.19.2-2.5.0

Give it a try and let me know. I understand it has been a minute since I have worked on this project. :)
