### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because "url" is null

### ISSUE THREAD

**Issue by yqs112358** [rmnaderdev/Whitelist-Sync-2#31]
The server will crash after newly installed Whitelist-Sync-2. It seems that the configuration file has not been processed well.

### Crash Info

```
--- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-12-22 21:32:15
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because "url" is null
	at knot//net.rmnad.core.shade.com.electronwill.nightconfig.core.file.FileNotFoundAction.lambda$copyData$3(FileNotFoundAction.java:51)
	at knot//net.rmnad.core.shade.com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215)
	at knot//net.rmnad.core.shade.com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at knot//net.rmnad.core.shade.com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138)
	at knot//net.rmnad.core.shade.com.electronwill.nightconfig.core.file.AutosaveFileConfig.load(AutosaveFileConfig.java:62)
	at knot//net.rmnad.core.config.WhitelistSyncConfig.load(WhitelistSyncConfig.java:70)
	at knot//net.rmnad.core.WhitelistSyncCore.LoadConfig(WhitelistSyncCore.java:20)
	at knot//net.rmnad.fabric_1_21_3.WhitelistSync2.lambda$onInitialize$1(WhitelistSync2.java:22)
	at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at knot//net.minecraft.server.MinecraftServer.handler$zeb000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2704)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:682)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Mods list
- Minecraft Server 1.21.3
- Fabric
- Fabric API 0.112.1
- WhitelistSync-2.8.0

**Comment by rmnaderdev** [comment]
Thank you for the report. I will see if I can reproduce this issue.

**Comment by rmnaderdev** [comment]
This was an error on my part with the refactor. The default config resource name had the bugged config file name with different casing so it couldn't find the correct default file. I will push out v2.8.1 today to fix this bug.

**Comment by rmnaderdev** [comment]
https://modrinth.com/mod/whitelistsync2/version/1.21.3-2.8.1
